### ISSUE TITLE
Get Unifi donwload failed

### ISSUE THREAD

**Issue by Fixel2012** [naphta/unifi#4]
Hi,

Frist of all I'm new to docker...

I'm trying to get any unifi controller on my Raspi 4 Docker environment running.

I managed to build my own docker container out of you'r repo with: `docker build github.com/naphta/unifi`

At the Task "TASK [Get UniFi]" I get the following error. `TASK [Get UniFi] ***************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failure downloading https://dl.ubnt.com/unifi//UniFi.unix.zip, HTTP Error 404: Not Found"}
        to retry, use: --limit @/etc/unifi/build.retry
`

Obviously the file is not anymore available at this location. I tried to replace it with  [this](https://dl.ui.com/unifi/5.12.35/unifi_sysvinit_all.deb) one. I already thought this won't work.

Can you help me out with this?

Can I use the documentation from jacobalberty/unifi-docker for your fork?

Thanks in advance.

**Comment by naphta** [comment]
There's a build argument of "unifi_version" which needs to be set during the docker build. If you pass in `--build-arg unifi_version=5.12.35` (you may need to add a v, on mobile and can't remember!) you should have better luck. I should really add some error handling around that value being null.

The documentation has diverged a fair bit now but if you intend to use it self contained and outside of kubernetes my prebuilt all-in-one image should serve just fine for you! If I recall correctly there's a build argument for `self_contained=true/false` which when set to true installs mongodb within the container too.

**Comment by Fixel2012** [comment]
All right!

Building the image without "self_contained=true/false" works fine.

with "self_contained=true" `docker build github.com/naphta/unifi --build-arg unifi_version=5.12.35 --build-arg self_contained=true`

does not work:
```
TASK [Install MongoDB] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'mongodb-org' is available"}
        to retry, use: --limit @/etc/unifi/build.retry

```

I think the all in one solution might be the easiest. So I would like to try this one.

Can you help me out with this error? Also which command will be the right to start the whole container.

Sorry for all the questions.

**Comment by naphta** [comment]
Ah that's a little strange, I'm not having a problem specifically on my mac at the moment running that command. I don't have my pi to hand to test a docker build on there.

Have you tried using my precompiled images?

```docker pull jakehilluk/unifi:v5.12.35-all-in-one```

**Comment by Fixel2012** [comment]
I didn't find the images on docker hub so far... Thank you.

But anyway there is still an error about the architecture:
 `
v5.12.35-all-in-one: Pulling from jakehilluk/unifi
no matching manifest for linux/arm/v7 in the manifest list entries`

So you'r container can also be started with [this ](https://github.com/jacobalberty/unifi-docker#description)Description? :)

**Comment by naphta** [comment]
Ah, I'm not supporting v7 just yet, it shouldn't be hard to though; I'll take a look today to see if I can get a manifest up for v7. On my Pi4 I've installed it using ARM64 as opposed to V7.

**Comment by naphta** [comment]
It's absolutely just down to the OS, or how it being loaded. The Pi 3 and Pi 4 both support 64 bit.

Take a look at https://wiki.ubuntu.com/ARM/RaspberryPi#Ubuntu_arm64.2FAArch64 it's from Ubuntu but it might help if you're using Debian (or Raspbian).

**Comment by Fixel2012** [comment]
Damn, I'm feeling so dumb.

Managed to get to armv8 now! So for my understanding the Pi should support 64 Bit now. Thank you....!

`:/home/pi# arch
aarch64`

`Raspi 4.19.106-v8+ #1297 SMP PREEMPT Tue Feb 25 13:31:10 GMT 2020 aarch64 GNU/Linux`

Anyway the docker pull commands fails for the same reason.

`root@Docker-Raspi:/home/pi# docker pull jakehilluk/unifi:v5.12.35-all-in-one
v5.12.35-all-in-one: Pulling from jakehilluk/unifi
no matching manifest for linux/arm/v8 in the manifest list entries
`

**Comment by naphta** [comment]
Not having that problem on my Pi, is this a fresh install? I'm wondering if you have a 32 bit docker running with multiarch, may be worth checking down that path?

```
root@local-rpi-01:~# uname -a
Linux local-rpi-01 5.3.0-1008-raspi2 #9-Ubuntu SMP Fri Oct 18 13:26:35 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```

```
root@local-rpi-01:~# apt-cache policy docker
docker:
  Installed: (none)
  Candidate: 1.5-2
  Version table:
     1.5-2 500
        500 http://ports.ubuntu.com/ubuntu-ports eoan/universe arm64 Packages
```

**Comment by naphta** [comment]
I figure either my last advice worked or you have a new solution? Closing for now in any case.
